//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClockShopEntities : DbContext
    {
        public ClockShopEntities()
            : base("name=ClockShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Fix> Fixes { get; set; }
        public virtual DbSet<Matche> Matches { get; set; }
        public virtual DbSet<Model> Models { get; set; }
        public virtual DbSet<SalesAndReturn> SalesAndReturns { get; set; }
        public virtual DbSet<StockDetail> StockDetails { get; set; }
        public object Company { get; internal set; }
    }
}
