//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fix
    {
        public int FixID { get; set; }
        public Nullable<System.DateTime> DateGet { get; set; }
        public Nullable<int> StokDetailID { get; set; }
        public Nullable<int> CustID { get; set; }
        public string DescribeProblem { get; set; }
        public Nullable<bool> WarrantyCard { get; set; }
        public Nullable<int> FixPrice { get; set; }
        public Nullable<bool> AgreeCust { get; set; }
        public string Statuss { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
