//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesAndReturn
    {
        public int SaleID { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<int> StokDetailID { get; set; }
        public Nullable<int> CustID { get; set; }
        public Nullable<double> SalePrice { get; set; }
        public Nullable<int> NumItem { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual StockDetail StockDetail { get; set; }
    }
}
