//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockDetail()
        {
            this.SalesAndReturns = new HashSet<SalesAndReturn>();
        }
    
        public int StokDetailID { get; set; }
        public Nullable<System.DateTime> DateIncomeStock { get; set; }
        public Nullable<int> NumUnitStock { get; set; }
        public Nullable<int> ModeID { get; set; }
        public Nullable<int> ColorID { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Model Model { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesAndReturn> SalesAndReturns { get; set; }
    }
}
